**Data Preprocessing..**

***Topic 01-- Data Inspection***

In [60]:
import pandas as pd

In [61]:
data = {
    "Age": [25, 30, 35, 40, 28, 30],
    "Salary": [30000, 40000, None, 60000, 35000, 40000],
    "Gender": ["Male", "Female", "Male", "Female", None, "Female"],
    "City": ["Dhaka", "Dhaka", "Chittagong", "Dhaka", "Rajshahi", "Dhaka"]
}

df = pd.DataFrame(data)

In [62]:
df.head()

   Age   Salary  Gender        City
0   25  30000.0    Male       Dhaka
1   30  40000.0  Female       Dhaka
2   35      NaN    Male  Chittagong
3   40  60000.0  Female       Dhaka
4   28  35000.0    None    Rajshahi

In [63]:
df.shape

(6, 4)

In [64]:
df.columns

Index(['Age', 'Salary', 'Gender', 'City'], dtype='object')

In [65]:
df.dtypes

Age         int64
Salary    float64
Gender     object
City       object
dtype: object

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     6 non-null      int64
 1   Salary  5 non-null      float64
 2   Gender  5 non-null      object
 3   City    6 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

In [67]:
df.describe()

             Age        Salary
count   6.000000      5.000000
mean   31.333333  41000.000000
std     5.354126  11401.754251
min    25.000000  30000.000000
25%    28.500000  35000.000000
50%    30.000000  40000.000000
75%    33.750000  40000.000000
max    40.000000  60000.000000

In [68]:
df.isnull().sum()

Age       0
Salary    1
Gender    1
City      0
dtype: int64

In [69]:
df.duplicated().sum()

np.int64(1)

***Topic 02 — Missing Values***

In [70]:
df.isnull().sum()

Age       0
Salary    1
Gender    1
City      0
dtype: int64

In [71]:
(df.isnull().mean() * 100 ).round(2)

Age        0.00
Salary    16.67
Gender    16.67
City       0.00
dtype: float64

In [72]:
df['Salary'].fillna(df['Salary'].median(), inplace=True)

/tmp/ipykernel_58/2984858743.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(), inplace=True)

In [73]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

/tmp/ipykernel_58/3657246551.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

In [74]:
df.isnull().sum()

Age       0
Salary    0
Gender    0
City      0
dtype: int64